Handle unmounting busy destination partitions

diff --git a/rpi-clone b/rpi-clone
--- a/rpi-clone
+++ b/rpi-clone
@@ -111,14 +111,54 @@ then
 	exit 0
 fi
 
+unmount_or_abort()
+	{
+	echo -n "Do you want to unmount $1? (yes/no): "
+	read resp
+	if [ "$resp" = "y" ] || [ "$resp" = "yes" ]
+	then
+		if ! umount $1
+		then
+			echo "Sorry, $PGM could not unmount $1."
+			echo -e "Aborting!\n"
+			exit 0
+		fi
+	else
+		echo -e "Aborting!\n"
+		exit 0
+	fi
+	}
+
+DST_ROOT_PARTITION=/dev/${DST_DISK}2
+DST_BOOT_PARTITION=/dev/${DST_DISK}1
+
+# Check that none of the destination partitions are busy (mounted).
+#
+DST_ROOT_CURMOUNT=`fgrep "$DST_ROOT_PARTITION " /etc/mtab | cut -f 2 -d ' ' `
+DST_BOOT_CURMOUNT=`fgrep "$DST_BOOT_PARTITION " /etc/mtab | cut -f 2 -d ' ' `
+
+if [ "$DST_ROOT_CURMOUNT" != "" ] || [ "$DST_BOOT_CURMOUNT" != "" ]
+then
+	echo "A destination partition is busy (mounted).  Mount status:"
+	echo "    $DST_ROOT_PARTITION:  $DST_ROOT_CURMOUNT"
+	echo "    $DST_BOOT_PARTITION:  $DST_BOOT_CURMOUNT"
+	if [ "$DST_BOOT_CURMOUNT" != "" ]
+	then
+		unmount_or_abort $DST_BOOT_CURMOUNT
+	fi
+	if [ "$DST_ROOT_CURMOUNT" != "" ]
+	then
+		unmount_or_abort $DST_ROOT_CURMOUNT
+	fi
+fi
+
 
 TEST_MOUNTED=`fgrep " $CLONE " /etc/mtab | cut -f 1 -d ' ' `
 if [ "$TEST_MOUNTED" != "" ]
 then
 	echo "This script uses $CLONE for mounting filesystems, but"
 	echo "$CLONE is already mounted with $TEST_MOUNTED."
-	echo -e "Unmount $CLONE before running this script.\n"
-	exit 0
+	unmount_or_abort $CLONE 
 fi
 
 if [ ! -d $CLONE ]
@@ -129,8 +169,8 @@ then
 		mkdir $CLONE
 	else
 		echo "$MNT_MOUNT is currently mounted on /mnt."
-		echo -e "Unmount /mnt before running $PGM.\n"
-		exit 0
+		unmount_or_abort /mnt
+		mkdir $CLONE
 	fi
 fi
 
@@ -161,23 +201,6 @@ EOF
 
 # =========== Disk Setup and Checks ===========
 #
-DST_ROOT_PARTITION=/dev/${DST_DISK}2
-DST_BOOT_PARTITION=/dev/${DST_DISK}1
-
-# Check that none of the destination partitions are busy (mounted).
-#
-DST_ROOT_CURMOUNT=`fgrep "$DST_ROOT_PARTITION " /etc/mtab | cut -f 2 -d ' ' `
-DST_BOOT_CURMOUNT=`fgrep "$DST_BOOT_PARTITION " /etc/mtab | cut -f 2 -d ' ' `
-
-if [ "$DST_ROOT_CURMOUNT" != "" ] || [ "$DST_BOOT_CURMOUNT" != "" ]
-then
-	echo "A destination partition is busy (mounted).  Mount status:"
-	echo "    $DST_ROOT_PARTITION:  $DST_ROOT_CURMOUNT"
-	echo "    $DST_BOOT_PARTITION:  $DST_BOOT_CURMOUNT"
-	echo -e "Aborting!\n"
-	exit 0
-fi
-
 # Check that destination partitions are the right type.
 #
 DST_BOOT_PARTITION_TYPE=`parted /dev/$DST_DISK -ms p \
